name: Build and Deploy JavaFX Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.0

      - name: Set up JDK 23
        uses: actions/setup-java@v3.0.0
        with:
          java-version: '23'
          distribution: 'adopt'

      - name: Package the application as a JAR
        run: mvn clean package

      - name: Verify Build Output
        run: ls -alh target

      - name: Create JAR file
        run: |
          mkdir -p docs/downloads
          cp target/*.jar docs/downloads/advent-calendar.jar
          ls -alh docs/downloads

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: advent-calendar-jar
          path: docs/downloads/advent-calendar.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: advent-calendar-jar
          path: ./docs/downloads

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.itp2 }}
          publish_dir: ./docs